/** --- YAML
 * name: 00080_rebook_suggestions
 * description: AI-based rebook loop — scans clients with established cadence, finds free typical slot in master calendar, pushes suggestion to master for approval, then TG-messages the client with 1-click rebook.
 * created: 2026-04-24
 * --- */

-- ─────────────────────────────────────────────────────────────
-- 1. Rebook suggestions (generated by cron, approved by master)
-- ─────────────────────────────────────────────────────────────
create table if not exists public.rebook_suggestions (
  id uuid primary key default gen_random_uuid(),
  master_id uuid not null references public.masters(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  service_id uuid not null references public.services(id) on delete set null,

  -- What AI computed
  median_interval_days int not null,            -- e.g. 28 ≈ monthly
  last_visit_at timestamptz not null,
  suggested_starts_at timestamptz not null,     -- first free slot matching cadence
  suggested_duration_min int not null,          -- from service
  alt_slots jsonb not null default '[]',        -- up to 2 alternative times [{starts_at}]

  -- Workflow state machine
  status text not null default 'pending_master'
    check (status in (
      'pending_master',    -- awaits master approval
      'dismissed_master',  -- master rejected
      'sent_client',       -- TG message sent to client
      'accepted',          -- client chose a slot, appointment created
      'declined',          -- client said no
      'stale',             -- slot got booked by another appt before client chose
      'expired'            -- client didn't respond in N days
    )),

  appointment_id uuid references public.appointments(id) on delete set null,

  -- Timestamps per state
  created_at timestamptz not null default now(),
  approved_by_master_at timestamptz,
  sent_to_client_at timestamptz,
  client_responded_at timestamptz,

  -- Anti-spam: only one active suggestion per (master, client) at a time
  unique(master_id, client_id, last_visit_at)
);

create index if not exists idx_rebook_master_status on public.rebook_suggestions(master_id, status);
create index if not exists idx_rebook_client_status on public.rebook_suggestions(client_id, status);
create index if not exists idx_rebook_suggested_slot on public.rebook_suggestions(suggested_starts_at) where status in ('pending_master', 'sent_client');

alter table public.rebook_suggestions enable row level security;

-- Master sees only their own suggestions
drop policy if exists "rebook_master_read" on public.rebook_suggestions;
create policy "rebook_master_read" on public.rebook_suggestions
  for select using (
    master_id in (select id from public.masters where profile_id = auth.uid())
  );

drop policy if exists "rebook_master_update" on public.rebook_suggestions;
create policy "rebook_master_update" on public.rebook_suggestions
  for update using (
    master_id in (select id from public.masters where profile_id = auth.uid())
  );

-- Client (if they have a profile_id) sees suggestions addressed to them
drop policy if exists "rebook_client_read" on public.rebook_suggestions;
create policy "rebook_client_read" on public.rebook_suggestions
  for select using (
    client_id in (select id from public.clients where profile_id = auth.uid())
  );

-- ─────────────────────────────────────────────────────────────
-- 2. Per-master rebook settings
-- ─────────────────────────────────────────────────────────────
alter table public.masters
  add column if not exists rebook_enabled boolean not null default true,
  add column if not exists rebook_min_interval_days int not null default 14,   -- don't suggest earlier than N days
  add column if not exists rebook_max_interval_days int not null default 120;  -- don't suggest for "rare" clients

comment on column public.masters.rebook_enabled is 'Master opt-in for automatic rebook suggestions. Default TRUE.';

-- ─────────────────────────────────────────────────────────────
-- 3. Helper: compute median visit interval for a (master, client) pair
-- ─────────────────────────────────────────────────────────────
create or replace function public.compute_client_visit_cadence(
  p_master_id uuid,
  p_client_id uuid
)
returns table (
  median_interval_days int,
  visits_count int,
  last_visit_at timestamptz,
  typical_dow int,        -- 0=Sun..6=Sat — most common day of week
  typical_hour int        -- 0..23 — most common hour
)
language plpgsql
stable
as $$
declare
  v_intervals int[];
  v_median int;
begin
  -- Get completed visits in chronological order (last 12 months)
  with visits as (
    select starts_at
    from public.appointments
    where master_id = p_master_id
      and client_id = p_client_id
      and status = 'completed'
      and starts_at > now() - interval '12 months'
    order by starts_at
  ),
  intervals as (
    select extract(epoch from (starts_at - lag(starts_at) over (order by starts_at))) / 86400 as days
    from visits
  )
  select array_agg(days::int) into v_intervals
  from intervals where days is not null;

  if v_intervals is null or array_length(v_intervals, 1) < 2 then
    return;  -- not enough data (need 3+ completed visits)
  end if;

  -- Median
  select (percentile_cont(0.5) within group (order by unnest))::int into v_median
  from unnest(v_intervals);

  return query
  select
    v_median,
    array_length(v_intervals, 1) + 1,
    (select max(starts_at) from public.appointments
      where master_id = p_master_id and client_id = p_client_id and status = 'completed'),
    (select mode() within group (order by extract(dow from starts_at)::int)
      from public.appointments
      where master_id = p_master_id and client_id = p_client_id and status = 'completed'),
    (select mode() within group (order by extract(hour from starts_at)::int)
      from public.appointments
      where master_id = p_master_id and client_id = p_client_id and status = 'completed');
end;
$$;

-- ─────────────────────────────────────────────────────────────
-- 4. Helper: check if a proposed time slot conflicts with master's schedule
-- ─────────────────────────────────────────────────────────────
create or replace function public.is_slot_free(
  p_master_id uuid,
  p_starts_at timestamptz,
  p_duration_min int
)
returns boolean
language sql
stable
as $$
  select not exists (
    select 1 from public.appointments
    where master_id = p_master_id
      and status in ('booked', 'confirmed', 'in_progress')
      and tstzrange(starts_at, ends_at, '[)') &&
          tstzrange(p_starts_at, p_starts_at + make_interval(mins => p_duration_min), '[)')
  );
$$;

grant execute on function public.compute_client_visit_cadence(uuid, uuid) to authenticated, service_role;
grant execute on function public.is_slot_free(uuid, timestamptz, int) to authenticated, service_role;

comment on table public.rebook_suggestions is 'AI-generated rebook proposals. Lifecycle: pending_master → sent_client → accepted/declined. See src/lib/rebook/';
