/** --- YAML
 * name: 00087_public_marketplace
 * description: Phase 3 — public marketplace. Masters get SEO-friendly slugs,
 *              public-read RLS for profile data, geo indexes for /search.
 *              /m/[slug] pages become indexable by Google.
 * created: 2026-04-24
 * --- */

-- 1. Slug + SEO fields on masters
alter table public.masters
  add column if not exists slug text unique,
  add column if not exists headline text,          -- one-line description for OG
  add column if not exists is_public boolean not null default false;

comment on column public.masters.slug is
  'URL-friendly unique identifier. Format: {firstname}-{service}-{city} e.g. anna-manicure-kyiv. Generated by backend.';
comment on column public.masters.is_public is
  'Master opted in to public marketplace. Off by default (privacy). When on, /m/{slug} is indexable + appears in /search.';

create index if not exists idx_masters_public_city on public.masters(city) where is_public = true;
create index if not exists idx_masters_public_active on public.masters(is_public, is_active) where is_public = true and is_active = true;

-- 2. Slug generation function (server uses this when master opts-in)
create or replace function public.generate_master_slug(
  p_full_name text,
  p_specialization text,
  p_city text
)
returns text
language plpgsql
stable
as $$
declare
  v_base text;
  v_candidate text;
  v_suffix int := 0;
begin
  -- Simple slug: lowercase, replace non-alphanumeric with hyphens, collapse
  v_base := lower(coalesce(p_full_name, 'master'));
  if p_specialization is not null and length(p_specialization) > 0 then
    v_base := v_base || '-' || lower(p_specialization);
  end if;
  if p_city is not null and length(p_city) > 0 then
    v_base := v_base || '-' || lower(p_city);
  end if;

  -- Transliterate common Cyrillic chars (keep it small — full translit table is too heavy)
  v_base := translate(
    v_base,
    'абвгдеёжзийклмнопрстуфхцчшщъыьэюяїєґі',
    'abvgdeejzijklmnoprstufhcchshsh_y_euaiyegi'
  );
  -- Strip non [a-z0-9] to -
  v_base := regexp_replace(v_base, '[^a-z0-9]+', '-', 'g');
  -- Collapse multiple dashes + trim
  v_base := trim(both '-' from regexp_replace(v_base, '-+', '-', 'g'));
  if length(v_base) = 0 then v_base := 'master'; end if;
  if length(v_base) > 60 then v_base := substr(v_base, 1, 60); end if;

  v_candidate := v_base;
  while exists (select 1 from public.masters where slug = v_candidate) loop
    v_suffix := v_suffix + 1;
    v_candidate := v_base || '-' || v_suffix::text;
  end loop;
  return v_candidate;
end;
$$;

grant execute on function public.generate_master_slug(text, text, text) to authenticated, service_role;

-- 3. Public RLS on masters (read-only, only is_public = true)
drop policy if exists "masters_public_read" on public.masters;
create policy "masters_public_read" on public.masters
  for select using (is_public = true and is_active = true);

-- 4. Public read on services of public masters
drop policy if exists "services_public_read" on public.services;
create policy "services_public_read" on public.services
  for select using (
    is_active = true
    and master_id in (select id from public.masters where is_public = true and is_active = true)
  );

-- 5. Public read on reviews for public masters
-- (polymorphic reviews: target_type = 'master', target_id = master.id)
drop policy if exists "reviews_public_master_read" on public.reviews;
create policy "reviews_public_master_read" on public.reviews
  for select using (
    is_published = true
    and target_type = 'master'
    and target_id in (select id from public.masters where is_public = true and is_active = true)
  );

-- 6. Rating aggregate (materialised-style computed column would be nicer; for MVP compute on read)
create or replace view public.master_ratings as
select
  m.id as master_id,
  count(r.id)::int as reviews_count,
  round(avg(r.score)::numeric, 2) as average_score
from public.masters m
left join public.reviews r
  on r.target_type = 'master'
  and r.target_id = m.id
  and r.is_published = true
where m.is_public = true
group by m.id;

grant select on public.master_ratings to anon, authenticated;

comment on view public.master_ratings is
  'Aggregated stats per public master. Used on /m/[slug] and /search.';
