/** --- YAML
 * name: Industry Categories Seed
 * description: Сидим 10 системных категорий + 128 подкатегорий. ON CONFLICT
 *              DO NOTHING — миграция идемпотентна, можно гонять заново.
 * created: 2026-05-10
 * --- */

INSERT INTO public.industry_categories (key, name_ru, name_uk, name_en, icon, is_system, status, sort_order, legacy_vertical_key) VALUES
  ('beauty',    'Красота',         'Краса',           'Beauty',         'scissors',     true, 'active', 10, 'beauty'),
  ('wellness',  'Здоровье и SPA',  'Здоровʼя та SPA', 'Wellness & SPA', 'hand-helping', true, 'active', 20, 'health'),
  ('medical',   'Медицина',        'Медицина',        'Medical',        'stethoscope',  true, 'active', 30, 'health'),
  ('pets',      'Питомцы',         'Тварини',         'Pets',           'paw-print',    true, 'active', 40, 'pets'),
  ('auto',      'Авто',            'Авто',            'Auto',           'car',          true, 'active', 50, 'auto'),
  ('home',      'Дом и ремонт',    'Дім та ремонт',   'Home & Repair',  'wrench',       true, 'active', 60, 'craft'),
  ('fitness',   'Фитнес',          'Фітнес',          'Fitness',        'dumbbell',     true, 'active', 70, 'fitness'),
  ('education', 'Образование',     'Освіта',          'Education',      'graduation-cap', true, 'active', 80, 'education'),
  ('events',    'События',         'Події',           'Events',         'party-popper', true, 'active', 90, 'events'),
  ('tattoo',    'Тату и пирсинг',  'Тату і пірсинг',  'Tattoo & Piercing', 'palette',  true, 'active', 100, 'tattoo')
ON CONFLICT (key) DO NOTHING;

WITH cat AS (
  SELECT id, key FROM public.industry_categories WHERE is_system = true
)
INSERT INTO public.industry_subcategories (category_id, key, name_ru, name_uk, name_en, is_system, status, sort_order)
SELECT cat.id, s.key, s.name_ru, s.name_uk, s.name_en, true, 'active', s.sort_order
FROM (VALUES
  ('beauty', 'hairdresser',     'Парикмахер',           'Перукар',                'Hairdresser',           10),
  ('beauty', 'barber',          'Барбер',               'Барбер',                 'Barber',                15),
  ('beauty', 'colorist',        'Колорист',             'Колорист',               'Colorist',              20),
  ('beauty', 'stylist',         'Стилист',              'Стиліст',                'Stylist',               25),
  ('beauty', 'manicure',        'Маникюр',              'Манікюр',                'Manicure',              30),
  ('beauty', 'pedicure',        'Педикюр',              'Педикюр',                'Pedicure',              35),
  ('beauty', 'nail_designer',   'Nail-дизайнер',        'Nail-дизайнер',          'Nail Designer',         40),
  ('beauty', 'brow_master',     'Brow-мастер',          'Brow-майстер',           'Brow Artist',           45),
  ('beauty', 'lash_master',     'Лэшмейкер',            'Лешмейкер',              'Lash Artist',           50),
  ('beauty', 'makeup',          'Визажист',             'Візажист',               'Makeup Artist',         55),
  ('beauty', 'cosmetologist',   'Косметолог',           'Косметолог',             'Esthetician',           60),
  ('beauty', 'wax',             'Восковая депиляция',   'Воскова депіляція',      'Waxing',                65),
  ('beauty', 'sugaring',        'Шугаринг',             'Шугаринг',               'Sugaring',              70),
  ('beauty', 'laser_hair',      'Лазерная эпиляция',    'Лазерна епіляція',       'Laser Hair Removal',    75),
  ('beauty', 'permanent',       'Перманентный макияж',  'Перманентний макіяж',    'Permanent Makeup',      80),
  ('beauty', 'tanning',         'Загар',                'Засмага',                'Tanning',               85),

  ('wellness', 'massage_classic',  'Массаж классический',     'Масаж класичний',         'Classic Massage',         10),
  ('wellness', 'massage_lymph',    'Лимфодренажный массаж',   'Лімфодренажний масаж',    'Lymphatic Drainage',      15),
  ('wellness', 'massage_sport',    'Спортивный массаж',       'Спортивний масаж',        'Sport Massage',           20),
  ('wellness', 'massage_spa',      'SPA-массаж',              'SPA-масаж',               'Spa Massage',             25),
  ('wellness', 'massage_relax',    'Расслабляющий массаж',    'Розслабляючий масаж',     'Relaxing Massage',        30),
  ('wellness', 'massage_anti',     'Антицеллюлитный массаж',  'Антицелюлітний масаж',    'Anti-cellulite Massage',  35),
  ('wellness', 'massage_thai',     'Тайский массаж',          'Тайський масаж',          'Thai Massage',            40),
  ('wellness', 'osteopath',       'Остеопат',                 'Остеопат',                'Osteopath',               45),
  ('wellness', 'manual',          'Мануальный терапевт',      'Мануальний терапевт',     'Manual Therapist',        50),
  ('wellness', 'reflex',          'Рефлексотерапия',          'Рефлексотерапія',         'Reflexology',             55),
  ('wellness', 'banya',           'Банщик',                   'Банщик',                  'Banya Master',            60),
  ('wellness', 'wraps',           'Обёртывания',              'Обгортання',              'Body Wraps',              65),
  ('wellness', 'stretching',      'Стретчинг',                'Стретчинг',               'Stretching',              70),

  ('medical', 'injectionist',  'Косметолог-инъекционист', 'Косметолог-ін''єкціоніст', 'Injection Cosmetologist', 10),
  ('medical', 'dermatologist', 'Дерматолог',              'Дерматолог',              'Dermatologist',           15),
  ('medical', 'dentist',       'Стоматолог',              'Стоматолог',              'Dentist',                 20),
  ('medical', 'gynecologist',  'Гинеколог',               'Гінеколог',               'Gynecologist',            25),
  ('medical', 'therapist',     'Терапевт',                'Терапевт',                'Physician',               30),
  ('medical', 'psychologist',  'Психолог',                'Психолог',                'Psychologist',            35),
  ('medical', 'psychotherap',  'Психотерапевт',           'Психотерапевт',           'Psychotherapist',         40),
  ('medical', 'speech',        'Логопед',                 'Логопед',                 'Speech Therapist',        45),
  ('medical', 'nutrition',     'Диетолог',                'Дієтолог',                'Nutritionist',            50),
  ('medical', 'endocrinol',    'Эндокринолог',            'Ендокринолог',            'Endocrinologist',         55),
  ('medical', 'neurologist',   'Невролог',                'Невролог',                'Neurologist',             60),
  ('medical', 'cardiologist',  'Кардиолог',               'Кардіолог',               'Cardiologist',            65),

  ('pets', 'grooming',        'Груминг',                'Грумінг',                'Grooming',                10),
  ('pets', 'trimming',        'Тримминг',               'Тримінг',                'Trimming',                15),
  ('pets', 'dog_haircut',     'Стрижка собак',          'Стрижка собак',          'Dog Haircut',             20),
  ('pets', 'cat_haircut',     'Стрижка кошек',          'Стрижка котів',          'Cat Haircut',             25),
  ('pets', 'vet',             'Ветеринар',              'Ветеринар',              'Veterinarian',            30),
  ('pets', 'handler',         'Хендлер',                'Хендлер',                'Handler',                 35),
  ('pets', 'trainer',         'Дрессировщик',           'Дресирувальник',         'Trainer',                 40),
  ('pets', 'sitter',          'Зооняня',                'Зооняня',                'Pet Sitter',              45),
  ('pets', 'walker',          'Выгул',                  'Вигул',                  'Dog Walker',              50),
  ('pets', 'boarding',        'Передержка',             'Передержка',             'Boarding',                55),
  ('pets', 'taxi',            'Зоотакси',               'Зоотаксі',               'Pet Taxi',                60),

  ('auto', 'service',     'СТО',                'СТО',                'Auto Service',         10),
  ('auto', 'wash',        'Мойка',              'Мийка',              'Car Wash',             15),
  ('auto', 'detailing',   'Детейлинг',          'Детейлінг',          'Detailing',            20),
  ('auto', 'tire',        'Шиномонтаж',         'Шиномонтаж',         'Tire Service',         25),
  ('auto', 'electric',    'Автоэлектрик',       'Автоелектрик',       'Auto Electrician',     30),
  ('auto', 'body',        'Кузовные работы',    'Кузовні роботи',     'Body Repair',          35),
  ('auto', 'paint',       'Покраска',           'Фарбування',         'Paint Job',            40),
  ('auto', 'polish',      'Полировка',          'Поліровка',          'Polishing',            45),
  ('auto', 'tint',        'Тонировка',          'Тонування',          'Window Tinting',       50),
  ('auto', 'alarm',       'Сигнализации',       'Сигналізації',       'Alarms',               55),
  ('auto', 'alignment',   'Развал-схождение',   'Розвал-сходження',   'Wheel Alignment',      60),
  ('auto', 'oil',         'Замена масла',       'Заміна оливи',       'Oil Change',           65),
  ('auto', 'diagnostics', 'Диагностика',        'Діагностика',        'Diagnostics',          70),
  ('auto', 'transmission','Ремонт АКПП',        'Ремонт АКПП',        'Transmission Repair',  75),

  ('home', 'electric',      'Электрик',          'Електрик',          'Electrician',           10),
  ('home', 'plumber',       'Сантехник',         'Сантехнік',         'Plumber',               15),
  ('home', 'handyman',      'Мастер на час',     'Майстер на годину', 'Handyman',              20),
  ('home', 'cleaning',      'Уборка',            'Прибирання',        'Cleaning',              25),
  ('home', 'drycleaning',   'Химчистка',         'Хімчистка',         'Dry Cleaning',          30),
  ('home', 'appliance',     'Ремонт техники',    'Ремонт техніки',    'Appliance Repair',      35),
  ('home', 'renovation',    'Ремонт квартиры',   'Ремонт квартири',   'Apartment Renovation',  40),
  ('home', 'furniture',     'Сборка мебели',     'Збірка меблів',     'Furniture Assembly',    45),
  ('home', 'windows',       'Окна',              'Вікна',             'Windows',               50),
  ('home', 'ceiling',       'Натяжные потолки',  'Натяжні стелі',     'Stretch Ceilings',      55),
  ('home', 'aircon',        'Кондиционеры',      'Кондиціонери',      'Air Conditioning',      60),
  ('home', 'designer',      'Дизайнер интерьера','Дизайнер інтерʼєру','Interior Designer',     65),
  ('home', 'tailor',        'Швея',              'Швачка',            'Tailor',                70),
  ('home', 'restorer',      'Реставратор',       'Реставратор',       'Restorer',              75),
  ('home', 'shoe_repair',   'Ремонт обуви',      'Ремонт взуття',     'Shoe Repair',           80),
  ('home', 'jeweler',       'Ювелир',            'Ювелір',            'Jeweler',               85),
  ('home', 'locksmith',     'Ключник',           'Ключник',           'Locksmith',             90),

  ('fitness', 'personal_trainer', 'Персональный тренер', 'Персональний тренер', 'Personal Trainer',   10),
  ('fitness', 'yoga',             'Йога',                 'Йога',                 'Yoga',              15),
  ('fitness', 'pilates',          'Пилатес',              'Пілатес',              'Pilates',           20),
  ('fitness', 'crossfit',         'Кроссфит',             'Кросфіт',              'CrossFit',          25),
  ('fitness', 'stretching',       'Стретчинг',            'Стретчинг',            'Stretching',        30),
  ('fitness', 'boxing',           'Бокс',                 'Бокс',                 'Boxing',            35),
  ('fitness', 'dance',            'Танцы',                'Танці',                'Dance',             40),
  ('fitness', 'swim',             'Плавание',             'Плавання',             'Swimming',          45),
  ('fitness', 'run',              'Бег',                  'Біг',                  'Running',           50),
  ('fitness', 'functional',       'Функциональный тренинг','Функціональний тренінг','Functional Training', 55),
  ('fitness', 'strength',         'Силовой тренинг',      'Силовий тренінг',      'Strength Training', 60),

  ('education', 'tutor_school',   'Репетитор школьных предметов','Репетитор шкільних предметів','School Tutor', 10),
  ('education', 'english',        'Английский язык',      'Англійська мова',      'English',           15),
  ('education', 'math',           'Математика',           'Математика',           'Math',              20),
  ('education', 'znо',            'Подготовка к НМТ',     'Підготовка до НМТ',    'NMT/ZNO Prep',      25),
  ('education', 'music',          'Музыка',               'Музика',               'Music',             30),
  ('education', 'vocal',          'Вокал',                'Вокал',                'Vocal',             35),
  ('education', 'guitar',         'Гитара',               'Гітара',               'Guitar',            40),
  ('education', 'piano',          'Фортепиано',           'Фортепіано',           'Piano',             45),
  ('education', 'programming',    'Программирование',     'Програмування',        'Programming',       50),
  ('education', 'design_courses', 'Курсы дизайна',        'Курси дизайну',        'Design Courses',    55),
  ('education', 'french',         'Французский язык',     'Французька мова',      'French',            60),
  ('education', 'german',         'Немецкий язык',        'Німецька мова',        'German',            65),
  ('education', 'spanish',        'Испанский язык',       'Іспанська мова',       'Spanish',           70),
  ('education', 'polish',         'Польский язык',        'Польська мова',        'Polish',            75),
  ('education', 'ukrainian',      'Украинский язык',      'Українська мова',      'Ukrainian',         80),

  ('events', 'host',           'Ведущий',           'Ведучий',           'Host/MC',           10),
  ('events', 'photographer',   'Фотограф',          'Фотограф',          'Photographer',      15),
  ('events', 'videographer',   'Видеограф',         'Відеограф',         'Videographer',      20),
  ('events', 'dj',             'DJ',                'DJ',                'DJ',                25),
  ('events', 'decorator',      'Декоратор',         'Декоратор',         'Decorator',         30),
  ('events', 'animator',       'Аниматор',          'Аніматор',          'Animator',          35),
  ('events', 'show',           'Шоу-программа',     'Шоу-програма',      'Show Program',      40),
  ('events', 'catering',       'Кейтеринг',         'Кейтеринг',         'Catering',          45),
  ('events', 'candy_bar',      'Кенди-бар',         'Кенді-бар',         'Candy Bar',         50),
  ('events', 'florist',        'Флорист',           'Флорист',           'Florist',           55),
  ('events', 'wedding_planner','Свадебный распорядитель','Весільний розпорядник','Wedding Planner', 60),
  ('events', 'sound',          'Звукорежиссёр',     'Звукорежисер',      'Sound Engineer',    65),

  ('tattoo', 'tattoo',          'Тату-мастер',           'Тату-майстер',           'Tattoo Artist',     10),
  ('tattoo', 'piercing',        'Пирсер',                'Пірсер',                 'Piercer',           15),
  ('tattoo', 'tattoo_removal',  'Удаление тату',         'Видалення тату',         'Tattoo Removal',    20),
  ('tattoo', 'permanent_makeup','Перманентный макияж',   'Перманентний макіяж',    'Permanent Makeup',  25),
  ('tattoo', 'microblading',    'Микроблейдинг',         'Мікроблейдинг',          'Microblading',      30),
  ('tattoo', 'brow_tattoo',     'Татуаж бровей',         'Татуаж брів',            'Brow Tattoo',       35),
  ('tattoo', 'lip_tattoo',      'Татуаж губ',            'Татуаж губ',             'Lip Tattoo',        40)
) AS s(cat_key, key, name_ru, name_uk, name_en, sort_order)
JOIN cat ON cat.key = s.cat_key
ON CONFLICT (category_id, key) DO NOTHING;
