/** --- YAML
 * name: Marketplace settings
 * description: Master opts-in to public marketplace. Enables /m/[slug] indexing + appearance in /search.
 *              Slug is generated by backend on first opt-in from full_name + specialization + city.
 * created: 2026-04-24
 * --- */

'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Globe, ExternalLink, Loader2, Check, X } from 'lucide-react';
import { toast } from 'sonner';
import { createClient } from '@/lib/supabase/client';

export default function MarketplaceSettingsPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [isPublic, setIsPublic] = useState(false);
  const [slug, setSlug] = useState<string | null>(null);
  const [headline, setHeadline] = useState('');

  useEffect(() => {
    (async () => {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      const { data: m } = await supabase
        .from('masters')
        .select('is_public, slug, headline')
        .eq('profile_id', user.id)
        .maybeSingle();
      if (m) {
        setIsPublic(!!m.is_public);
        setSlug(m.slug ?? null);
        setHeadline(m.headline ?? '');
      }
      setLoading(false);
    })();
  }, []);

  const save = async () => {
    setSaving(true);
    try {
      const res = await fetch('/api/marketplace/master/opt-in', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ is_public: isPublic, headline: headline.trim() || null }),
      });
      const data = await res.json().catch(() => ({}));
      if (res.ok) {
        setSlug(data.slug ?? slug);
        toast.success(isPublic ? 'Профиль опубликован' : 'Профиль скрыт');
      } else {
        toast.error(data.error ?? 'Ошибка');
      }
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-10">
        <Loader2 className="size-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const publicUrl = slug ? `https://cres-ca.com/m/${slug}` : null;

  return (
    <div className="mx-auto max-w-2xl space-y-6 p-6 pb-12">
      <Link href="/settings" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground">
        <ArrowLeft className="size-3.5" />
        Настройки
      </Link>

      <div>
        <h1 className="flex items-center gap-2 text-2xl font-bold tracking-tight">
          <Globe className="size-6 text-primary" />
          Публичный маркетплейс
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Включи — твой профиль станет доступен в Google и в поиске CRES-CA. Клиенты смогут записаться к тебе через публичную страницу.
        </p>
      </div>

      <div className="rounded-2xl border border-border bg-card p-5 space-y-4">
        <label className="flex cursor-pointer items-start gap-3">
          <input
            type="checkbox"
            checked={isPublic}
            onChange={(e) => setIsPublic(e.target.checked)}
            className="mt-0.5 size-4 accent-primary"
          />
          <div>
            <p className="text-sm font-semibold">Опубликовать профиль</p>
            <p className="text-[12.5px] text-muted-foreground">
              Страница <code>/m/{slug ?? 'ваш-slug'}</code> будет видна в Google, Яндексе и внутреннем поиске. Всегда можно выключить — страница сразу выпадает из поиска.
            </p>
          </div>
        </label>

        <div>
          <label className="text-sm font-medium">Краткое описание (для соц-сетей)</label>
          <input
            type="text"
            value={headline}
            onChange={(e) => setHeadline(e.target.value.slice(0, 160))}
            placeholder="Напр. «Маникюр и педикюр в центре Киева. Работаю 5 лет»"
            className="mt-1.5 w-full rounded-xl border border-border bg-background p-2 text-sm outline-none focus:border-primary"
          />
          <p className="mt-1 text-[11px] text-muted-foreground">{headline.length}/160 · Показывается в Google и в превью когда кто-то делится ссылкой на твой профиль.</p>
        </div>

        <button
          onClick={save}
          disabled={saving}
          className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-60"
        >
          {saving ? <Loader2 className="size-4 animate-spin" /> : isPublic ? <Check className="size-4" /> : <X className="size-4" />}
          {saving ? 'Сохраняю…' : 'Сохранить'}
        </button>
      </div>

      {publicUrl && isPublic && (
        <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/5 p-5">
          <p className="text-sm font-semibold text-emerald-700 dark:text-emerald-300">Твой профиль опубликован</p>
          <a
            href={publicUrl}
            target="_blank"
            rel="noreferrer"
            className="mt-1 inline-flex items-center gap-1.5 text-sm text-emerald-700 underline dark:text-emerald-300"
          >
            <ExternalLink className="size-3.5" />
            {publicUrl}
          </a>
          <p className="mt-2 text-[12px] text-muted-foreground">
            Поделись этой ссылкой в соц-сетях, визитках, Telegram-канале. Google проиндексирует за 3-7 дней.
          </p>
        </div>
      )}
    </div>
  );
}
